spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/db_example
  jpa:
    hibernate:
      ddl-auto: update
server:
  error:
    include-message: always
